version: '3.2'

services:
  nestjs:
    image: nestjs-boilerplate-nestjs
    container_name: nestjs-boilerplate-nestjs
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - app-network
    env_file:
      - .env

  nginx:
    image: nginx:stable
    container_name: nestjs-boilerplate-nginx
    restart: always
    depends_on:
      - nestjs
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    ports:
      - 80:80
      - 443:443

networks:
  app-network:
    driver: bridge
