version: '3.2'

services:
  mariadb:
    image: mariadb:10.5.8
    container_name: nestjs-boilerplate-mariadb
    restart: always
    networks:
      - app-network
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/conf/mariadb.cnf:/etc/mysql/my.cnf
    env_file:
      - .env-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DEFAULT_DATABASE}
      TZ: ${DB_TIME_ZONE}

  nestjs:
    image: nestjs-boilerplate-nestjs-dev
    container_name: nestjs-boilerplate-nestjs-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    restart: always
    depends_on:
      - mariadb
    networks:
      - app-network
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env-dev
    ports:
      - 5000:5000

networks:
  app-network:
    driver: bridge
