name: Run backend test

on:
  pull_request:
    branches:
    - master

jobs:
  run-backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
        
      - name: Install packages
        run: npm ci
        working-directory: server

      - name: Run test
        run: |
          ./run-test.sh up
          npm run test
        working-directory: server
