name: Run test

on:
  pull_request:
    branches:
    - master

jobs:
  run-backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
        
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
         cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
          working-directory: server 

      - name: Install packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: server

      - name: Run test
        run: |
          ./run-test.sh up
          npm run test
        working-directory: server
