name: Run frontend test

on:
  pull_request:
    branches:
    - master

jobs:
  run-frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
        
      - name: Install packages
        run: yarn install --frozen-lockfile
        working-directory: webapp

      - name: Run test
        run: yarn test
        working-directory: webapp
